server:
  port: 8080
spring:
  application:
    name: AbcElasticJobSpringBootDemo
  main:
    banner-mode: off

elasticjob:
  jobs:
    TestJob1:
      description: 测试任务1
      # https://cron.qqe2.com/
      cron: 0/2 * * * * ?
      elastic-job-class: org.example.job.TestJob1
      # 分片，一般情况下设置为1
      sharding-total-count: 2
      sharding-item-parameters: 0=Beijing,1=Shanghai,2=Guangzhou
      # 失效转移
      failover: false
      # 错过重新执行
      misfire: false
      # 是否覆盖已存在作业
      overwrite: true
      # 禁止启动(true禁止，false开启)
      disabled: false
#    TestJob2:
#      description: 测试任务2
#      # https://cron.qqe2.com/
#      cron: 0/2 * * * * ?
#      elasticJobClass: org.example.job.TestJob2
#      # 分片，一般情况下设置为1
#      shardingTotalCount: 1
#      # 失效转移
#      failover: false
#      # 错过重新执行
#      misfire: false
#      # 是否覆盖已存在作业
#      overwrite: true
#      # 禁止启动(true禁止，false开启)
#      disabled: true
  regCenter:
    namespace: ELASTICJOB-DEV-TEST-NAMESPACE
    serverLists: localhost:2181
    max-retries: 3
    base-sleep-time-milliseconds: 1000
    max-sleep-time-milliseconds: 3000
    session-timeout-milliseconds: 6000
    connection-timeout-milliseconds: 6000